### ISSUE TITLE
Problème dégrèvement dégressif

### ISSUE THREAD

**Issue by bfabre01** [marion-paclot/TH#2]
Bonjour @marion-paclot ,

Merci beaucoup pour tout ce travail sur la TH !

Il me semble avoir remarqué une anomalie dans les résultats sur le dégrevement dégressif. J'ai fait un test sur l'appli pour calculer la TH pour le cas où:
  - RFR = 68400
  - 4 parts fiscales
  - 3 personnes à charge
  - Département : Ain, commune Bregnier Cordon
  - Valeur locative : 3000

Pour la simulation de la "réforme 2018", il est indiqué un taux de dégrèvement de 2%. Il semble qu'il y ait une erreur dans le seuil d'éligibilité au regard du RFR. Pour 4 parts fiscales, le dégrèvement dégressif a lieu entre 67 000 et 69 000. Et le taux doit être de 0.3 * (69000-68400)/(69000-67000) = 9%. En voyant la courbe sur l'appli, il me semble que la formule prend 61 000 au lieu de 67 000 (qui correspond au seuil pour 3.5 parts, et pas 4), ce qui donne en effet 2%.
(il s'agit des seuils 2018).

Confirmes-tu cela ?

**Comment by marion-paclot** [comment]
Bonjour et merci beaucoup pour avoir pris le temps de comprendre le problème.
J'ai effectivement laissé trainer un 3000 à la place de 6000 pour déterminer la valeur de la demi-part au delà de 3 parts (uniquement dans la détermination du seuil bas, le seuil haut était correct), et c'était une erreur. C'est corrigé et il faut maintenant que je m'assure que la modification est passée.

**Comment by bfabre01** [comment]
Merci pour ton retour. J'ai refait le même test, et ça marche maintenant ! Pour info, on est en train d'ajouter la TH dans openfisca (PR [ici](https://github.com/openfisca/openfisca-france/pull/1320) ), d'où le fait que j'ai utilisé ton appli pour comparer tes outputs aux miens.
